version: "3"
services:
  login:
    build: sb-login
    ports:
      - "8080:8080"
    links:
      - mysql
    command: ["./wait-for-it.sh", "db:3306", "java","-jar", "app.jar"]
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users
  ##counter:
    #container_name: sbcounter
    #restart: always
    #build: .
    #ports:
    #  - "8081:8080"
    #links:
     # - redis
  #photos:
    #container_name: sbphoto
    #restart: always
    #build: .
    #ports:
    #  - "8082:8080"
    #links:
    #  - mongo
    #  - swift
  #mongo:
    #container_name: mongo
    #image: mongo
    #volumes:
     # - mongodata:/data/db
    #ports:
    #  - "27017:27017"
  #swift:
   # container_name: swift
    #image: swift
    #ports:
     # - "8083:8080"
  #redis:
   # container_name: redis
    #image: "redis:alpine"
    #ports:
    #  - "6379:6379"
