version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users
  login:
    build: sb-login
    ports:
      - "8080:8080"
    environment: 
      - SECRET_TOKEN=secreto
      - DB_MYSQL_DNS=mysql
      - DB_MYSQL_USER=root
      - DB_MYSQL_PW=root
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=120
  swift:
    image: twcammaster.uv.es/swift
  mongodb:
    image: mongo
    ports:
      - 27017:27017
  photos:
    build: project
    ports:
      - 8082:8082
    environment:
      - SECRET_TOKEN=secreto
      - SWIFT_URL=http://swift:8080
      - SWIFT_USERNAME=test:tester
      - SWIFT_PASSWORD=testing,
      - MONGODB_URL=mongodb://mongodb/photo
  redis:
    image: redis
    ports:
      - 6379:6379
  counters:
    build: sb-counters
    ports: 
      - 8081:8081
    environment:
      - REDIS_COUNTERS_SERVICE_HOST=redis
      - SECRET_TOKEN=secreto

  ##counter:
    #container_name: sbcounter
    #restart: always
    #build: .
    #ports:
    #  - "8081:8080"
    #links:
     # - redis
  #photos:
    #container_name: sbphoto
    #restart: always
    #build: .
    #ports:
    #  - "8082:8080"
    #links:
    #  - mongo
    #  - swift
  #mongo:
    #container_name: mongo
    #image: mongo
    #volumes:
     # - mongodata:/data/db
    #ports:
    #  - "27017:27017"
  #swift:
   # container_name: swift
    #image: swift
    #ports:
     # - "8083:8080"
  #redis:
   # container_name: redis
    #image: "redis:alpine"
    #ports:
    #  - "6379:6379"
