version: "3.3"
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=superSecretPW
      - MYSQL_DATABASE=users
    networks:
      - network_g4 
  login:
    build: sb-login
    ports:
      - "8080:8080"
    networks:
      - network_g4
    configs:
      - my_config
  swift:
    image: twcammaster.uv.es/swift
    networks:
      - network_g4
  mongodb:
    image: mongo
    networks:
      - network_g4
  photos:
    build: project
    ports:
      - 8082:8082
    environment:
      - SECRET_TOKEN=secretSwarmSalt
      - SWIFT_URL=http://swift:8080
      - SWIFT_USERNAME=test:tester
      - SWIFT_PASSWORD=testing
      - MONGODB_URL=mongodb://mongodb/photo
    networks:
      - network_g4
  redis:
    image: redis
    networks:
      - network_g4
  counters:
    build: sb-counters
    ports: 
      - 8081:8090
    networks:
      - network_g4
    configs:
      - my_config
networks:
  network_g4:
configs:
  my_config:
    file: ./application.properties