version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users
  login:
    build: sb-login
    ports:
      - "8080:8080"
    links:
      - mysql
    environment: 
      - SECRET_TOKEN=secreto
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=120
  redis:
    #container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379" 
  counter:
    #container_name: sbcounter
    restart: always
    build: sb-counters
    ports:
      - "8081:8090"
    environment:
      - REDIS_COUNTERS_SERVICE_HOST=localhost
      - REDIS_COUNTERS_SERVICE_PORT=6379
      - SECRET_TOKEN=secreto
    links:
      - redis
  #photos:
    #container_name: sbphoto
    #restart: always
    #build: .
    #ports:
    #  - "8082:8080"
    #links:
    #  - mongo
    #  - swift
  #mongo:
    #container_name: mongo
    #image: mongo
    #volumes:
     # - mongodata:/data/db
    #ports:
    #  - "27017:27017"
  #swift:
   # container_name: swift
    #image: swift
    #ports:
     # - "8083:8080"
